/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsAttestation {
  trusted: boolean
  teeType: string
  measurement?: string
  tcbStatus: string
  advisoryIds: Array<string>
}
export interface JsRatlsConnection {
  socketId: number
  attestation: JsAttestation
}
/** Establish an RATLS connection and return a socket handle with attestation result */
export declare function ratlsConnect(targetHost: string, serverName: string): Promise<JsRatlsConnection>
/** Read data from socket */
export declare function socketRead(socketId: number, size?: number | undefined | null): Promise<Buffer>
/** Write data to socket */
export declare function socketWrite(socketId: number, data: Buffer): Promise<number>
/** Gracefully close the socket (flush + shutdown) */
export declare function socketClose(socketId: number): Promise<void>
/** Immediately destroy the socket */
export declare function socketDestroy(socketId: number): void
